// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import SearchController from "./search_controller";
application.register("search", SearchController);

import PwaController from "./pwa_controller";
application.register("pwa", PwaController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import SimpleEditorController from "./simple_editor_controller";
application.register("simple-editor", SimpleEditorController);

import EventPopupController from "./event_popup_controller";
application.register("event-popup", EventPopupController);

import QuickCaptureController from "./quick_capture_controller";
application.register("quick-capture", QuickCaptureController);

import FileUploadController from "./file_upload_controller";
application.register("file-upload", FileUploadController);

import SidebarController from "./sidebar_controller";
application.register("sidebar", SidebarController);

import TagInputController from "./tag_input_controller";
application.register("tag-input", TagInputController);

import TagFilterController from "./tag_filter_controller";
application.register("tag-filter", TagFilterController);

import AudioPlayerController from "./audio_player_controller";
application.register("audio-player", AudioPlayerController);

import AudioRecorderController from "./audio_recorder_controller";
application.register("audio-recorder", AudioRecorderController);

import DocumentAutosaveController from "./document_autosave_controller";
application.register("document-autosave", DocumentAutosaveController);

import TimeComboboxController from "./time_combobox_controller";
application.register("time-combobox", TimeComboboxController);

import CalendarEventFormController from "./calendar_event_form_controller";
application.register("calendar-event-form", CalendarEventFormController);

import TaskFormController from "./task_form_controller";
application.register("task-form", TaskFormController);

import WikiLinkController from "./wiki_link_controller";
application.register("wiki-link", WikiLinkController);

import StatusDropdownController from "./status_dropdown_controller";
application.register("status-dropdown", StatusDropdownController);

import ConnectedNotesController from "./connected_notes_controller";
application.register("connected-notes", ConnectedNotesController);

import StorageSettingsController from "./storage_settings_controller";
application.register("storage-settings", StorageSettingsController);
