// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DocumentEditorController from "./document_editor_controller";
application.register("document-editor", DocumentEditorController);

import SearchController from "./search_controller";
application.register("search", SearchController);

import SidebarController from "./sidebar_controller";
application.register("sidebar", SidebarController);

import PwaController from "./pwa_controller";
application.register("pwa", PwaController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);
